image: "python:3.9"

before_script:
  - apt-get update
  - apt-get install -y python3-enchant
  - python -m pip install --upgrade pip
  - pip install -e .[lint,test]

stages:
  - lint
  - test

isort:
  stage: lint
  script:
    - isort . --check

black:
  stage: lint
  script:
    - black . --check

flake8:
  stage: lint
  script:
    - flake8

mypy:
  stage: lint
  script:
    - python -m mypy .

spelling:
  stage: lint
  script:
    - pylint ./**/*.py

pytest:
  stage: test
  script:
    - pytest -v --cov
