default_language_version:
  python: python3.9

default_stages: [ commit, push ]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--check" ]

  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [ "--check" ]
        language_version: python3.9

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy

  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args: [ "./**/*.py" ]
        additional_dependencies:
          - pyenchant
