name: Static code analysis

on: [push]

jobs:
  run_static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Dependency installation
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-enchant
          python -m pip install --upgrade pip
          pip install -e .[lint]
      - name: isort
        run: isort . --check
      - name: black
        run: black . --check
      - name: flake8
        run: flake8
      - name: mypy
        run: python -m mypy .
      - name: pylint
        run: pylint ./**/*.py
